<?= $this->headTitle('Login') ?>
<?php
$email = $form->get('email');
$password = $form->get('password');
$submit = $form->get('submit');
$form->setAttribute('action', $this->url('login'));
$form->prepare();
echo $this->form()->openTag($form);
?>
<div class='container'>
    <div class="col-md-9" style="margin-left: 70px; margin-top: 50px;">
        <h2>Login</h2>
        <fieldset>
            <legend>Dados de autenticação</legend>

            <?php if ($messageError): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $messageError ?>
                </div>
            <?php endif; ?>

            <div class="form-group">
                <?= $this->formLabel($email) ?>
                <?= $this->formElement($email) ?>
            </div>

            <div class="form-group">
                <?= $this->formLabel($password) ?>
                <?= $this->formElement($password) ?>
                <br>
                <?php echo $this->formSubmit($submit); ?>
            </div>
        </fieldset>
    </div>
</div>

<?php
echo $this->form()->closeTag();
?>

